apiVersion: v1
kind: PersistentVolume
metadata:
  name: day-29-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/day-29
  storageClassName: manual