apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: day-29-pvc
  namespace: day-29
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual