apiVersion: v1
kind: Secret
metadata:
  name: day-29-secret
  namespace: day-29
type: Opaque
stringData:
  # Use stringData for plain text - Kubernetes will auto-encode to base64
  DB_PASSWORD: "superSecretPassword123"
  API_KEY: "sk_live_abc123xyz789"
  JWT_SECRET: "my-super-secret-jwt-token"